Improve README, comments; remove .sh from main file name

diff --git a/container-image-tags b/container-image-tags
--- a/container-image-tags
+++ b/container-image-tags
@@ -26,6 +26,7 @@
 #   4. Optionally find and print every current registry tag for that digest.
 #
 # Prerequisites:
+# - on macOS, Homebrew with gnu-getopt and coreutils installed,
 # - curl
 # - jq
 # - docker CLI
@@ -43,10 +44,6 @@
 # TIP:
 # - To list all the Repo digests for your containers:
 #    docker image ls --digests --format 'table {{.Repository}}\t{{.Tag}}\t{{.Digest}}\t{{.ID}}\t{{.CreatedSince}}\t{{.Size}}'
-# - To query all local containers:
-#   container-image-tags $(docker ps -a --format "{{.Names}}")
-#
-# 2026-08-22 Authored mostly by DeepSeek V4 Flash and OpenAI's GPT 5.6 Sol
 
 #### Preamble (v2026-08-24)
 
@@ -67,19 +64,16 @@ if [[ $OSTYPE == darwin* ]]; then
         { echo "$0: ERROR: \`$_install_cmd gnu-getopt\` to install $GETOPT." >&2; exit 1; }
     [[ -x "${REALPATH:="$HOMEBREW_PREFIX/bin/grealpath"}" ]] || \
         { echo "$0: ERROR: \`$_install_cmd coreutils\` to install $REALPATH." >&2; exit 1; }
-    [[ -x "${JQ:="$HOMEBREW_PREFIX/bin/jq"}" ]] || \
-        { echo "$0: ERROR: \`$_install_cmd jq\` to install $JQ." >&2; exit 1; }
-    DOCKER="${DOCKER:-$HOMEBREW_PREFIX/bin/docker}"
 else
     _install_cmd="sudo apt install"
-    GETOPT="getopt"
-    REALPATH="realpath"
-    command -v "${JQ:=jq}" &>/dev/null || \
-        { echo "$0: ERROR: \`$_install_cmd jq\` to install $JQ." >&2; exit 1; }
-    DOCKER="${DOCKER:-docker}"
+    GETOPT=${GETOPT:-getopt}
+    REALPATH=${REALPATH:-realpath}
 fi
 command -v "${CURL:=curl}" &>/dev/null ||
     { echo "$0: ERROR: \`$_install_cmd curl\` to install $CURL." >&2; exit 1; }
+command -v "${JQ:=jq}" &>/dev/null || \
+    { echo "$0: ERROR: \`$_install_cmd jq\` to install $JQ." >&2; exit 1; }
+DOCKER=${DOCKER:-docker}
 
 SCRIPT=$("$REALPATH" --no-symlinks "${BASH_SOURCE[0]}")
 # shellcheck disable=SC2034
